"""Generate a styled HTML report combining all visualisations."""

from pathlib import Path

import plotly.io as pio

from src.config import OUTPUT_DIR
from src.visualization.charts import create_all_charts
from src.visualization.diagrams import country_disaster_network


def generate_html_report(output_path: str | Path | None = None) -> Path:
    """Build and save the full HTML report with all charts and the network diagram.

    Returns the path to the generated HTML file.
    """
    if output_path is None:
        output_path = OUTPUT_DIR / "report.html"
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    charts = create_all_charts()
    network_fig = country_disaster_network()

    # Convert figures to HTML divs.
    # The FIRST chart embeds the full plotly.js bundle inline (self-contained);
    # the rest reuse the already-loaded library.
    chart_items = list(charts.items())
    chart_divs = ""
    for i, (name, fig) in enumerate(chart_items):
        title = name.replace("_", " ").title()
        div = pio.to_html(
            fig,
            full_html=False,
            include_plotlyjs=True if i == 0 else False,
        )
        chart_divs += f'<section class="chart-section"><h2>{title}</h2>{div}</section>\n'

    network_div = pio.to_html(network_fig, full_html=False, include_plotlyjs=False)

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Natural Disaster Analysis Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #f5f6fa;
            color: #2c3e50;
            line-height: 1.6;
        }}
        header {{
            background: linear-gradient(135deg, #2c3e50, #3498db);
            color: white;
            padding: 2rem;
            text-align: center;
        }}
        header h1 {{ font-size: 2rem; margin-bottom: 0.5rem; }}
        header p {{ opacity: 0.9; font-size: 1.1rem; }}
        .container {{ max-width: 1100px; margin: 2rem auto; padding: 0 1rem; }}
        .chart-section {{
            background: white;
            border-radius: 8px;
            padding: 1.5rem;
            margin-bottom: 2rem;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
        }}
        .chart-section h2 {{
            color: #2c3e50;
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 2px solid #3498db;
        }}
        footer {{
            text-align: center;
            padding: 2rem;
            color: #7f8c8d;
            font-size: 0.9rem;
        }}
    </style>
</head>
<body>
    <header>
        <h1>Natural Disaster Analysis Report</h1>
        <p>EM-DAT Dataset (1970&ndash;2021) &mdash; 14,644 disaster records across 228 countries</p>
    </header>
    <div class="container">
        <section class="chart-section">
            <h2>Data Overview</h2>
            <p>This report presents interactive visualisations of the EM-DAT international disaster database,
            covering natural disasters recorded between 1970 and 2021. The data includes information on
            disaster types, affected countries, mortality, and population impact.</p>
        </section>

        {chart_divs}

        <section class="chart-section">
            <h2>Country&ndash;Disaster Network</h2>
            <p>Countries are connected when they share 3 or more disaster types. Node size represents
            total disaster count; colour intensity shows the number of connections.</p>
            {network_div}
        </section>
    </div>
    <footer>
        Generated by Natural Disaster Chat App &bull; Data source: EM-DAT (CRED)
    </footer>
</body>
</html>
"""

    output_path.write_text(html)
    return output_path
